### ISSUE TITLE
Bug: If cluster_xpos and cluster_ypos are both not null, clustum is referenced before assignment

### ISSUE THREAD

**Issue by eveilyeverafter** [Nanostring-Biostats/InSituType#184]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/5805450/208168244-ec60bc97-e3d2-48a6-a793-720b464c81b1.png">

https://github.com/Nanostring-Biostats/InSituType/blob/07ae239a0d4125327c00c5c30094f68f938a89ee/R/flightpath_layout.R#L64-L65

**Comment by patrickjdanaher** [comment]
Fixed in upcoming 2.0 release
