### ISSUE TITLE
Problem on running semi-supervised method on reference matrix from Nanostring-CellProfile-Library

### ISSUE THREAD

**Issue by Sakura1a2a3a** [Nanostring-Biostats/InSituType#191]
I am trying to run the semi-supervise method, and I am using reference data Colon_HCA.RData from CellProfile Library linked from Manuscript. I also tried to use ioprofile which is given as example which works well, I am wondering why Colon_HCA.RData would cause an error. 
Here is what I did:

load("./Colon_HCA.RData")
pro <- as.matrix(profile_matrix)
select anchor cell...
get updated reference......
<img width="614" alt="Screenshot 2023-06-19 at 6 13 52 PM" src="https://github.com/Nanostring-Biostats/InSituType/assets/121363250/cedcf1ba-ccfc-43a0-9b3b-1710bddc1528">

<img width="593" alt="Screenshot 2023-06-19 at 6 14 59 PM" src="https://github.com/Nanostring-Biostats/InSituType/assets/121363250/824a620f-faea-4247-8e1d-4e592a224f68">

<img width="576" alt="Screenshot 2023-06-19 at 6 15 23 PM" src="https://github.com/Nanostring-Biostats/InSituType/assets/121363250/151ae26f-8857-4dce-b779-08077f659c06">

I am wondering why I can simply use ioprofile which would work, but I get an error when I use Colon profile. What should I do if I want to use profiles from Nanostring Profile-Profile -Library?

**Comment by patrickjdanaher** [comment]
I suspect this has something to do with the very small values input for n_phase1 etc. 

I'll change the vignettes to suggest higher values.
