### ISSUE TITLE
No tumor clusters found in NSCLC supervised vignette

### ISSUE THREAD

**Issue by binghama** [Nanostring-Biostats/InSituType#193]
When running the NSCLC vignette, I did not see a cluster identified as tumor. It does not seem that the reference table includes a profile for tumor cells - is this the case?

**Comment by patrickjdanaher** [comment]
That's right - that's the case. If this was an honest attempt at cell typing that tissue rather than a quick demo, you'd of course want a tumor profile. Sorry for the confusion.

**Comment by yubin-ai** [comment]
curious that why you would take tumor out of the demo? it is a NSCLC tissue... and it would be great to have tumor there.
