### ISSUE TITLE
bugs in geosketch and find_anchor_cells.R

### ISSUE THREAD

**Issue by jonathanperrie** [Nanostring-Biostats/InSituType#212]
Cannot install without getting rid of branching bugs 

geosketch 
https://gist.github.com/jonathanperrie/613ca31fbbc812eca085da84a8a8125c
anchor
https://gist.github.com/jonathanperrie/9c05a7bcd754703c2411c993fc2a3de8

**Comment by patrickjdanaher** [comment]
Thanks for the report and the fix! We've just merged fixes to this and another issue.
